[package]
name = "ch03-01-variables-and-mutability"
version = "0.1.0"
authors = ["user112"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
